Script started on Thu 04 Dec 2014 10:17:48 AM PST
~
abarb014@hammer $ cs100
[0;91m
===============================================================================
|                                                                             |
| You have enabled settings specific for cs100.                               |
|                                                                             |
===============================================================================
[0m
[s%%%%%%%%%%[u[0;32mabarb014[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m cd cs100/rshell
[s%%%%%%%%%%[u[0;32mabarb014[0;36m@[0;32mcs100[0;36m:[0;32m~/cs100/rshell[0;95m (signal) [0;36m$[0m make
mkdir -p bin
g++ -Wall -Werror -ansi -pedantic src/main.cpp -o bin/rshell
g++ -Wall -Werror -ansi -pedantic src/ls.cpp -o bin/ls
g++ -Wall -Werror -ansi -pedantic src/cp.cpp -o bin/cp
[s%%%%%%%%%%[u[0;32mabarb014[0;36m@[0;32mcs100[0;36m:[0;32m~/cs100/rshell[0;95m (signal) [0;36m$[0m bin/rshell
/home/csmajs/abarb014/cs100/rshell $ # my_exec tests
/home/csmajs/abarb014/cs100/rshell $ # Start with regular commands
/home/csmajs/abarb014/cs100/rshell $ ls
bin  LICENSE  Makefile	README.md  src	tests
/home/csmajs/abarb014/cs100/rshell $ pwd
/home/csmajs/abarb014/cs100/rshell
/home/csmajs/abarb014/cs100/rshell $ ls --color
[0m[38;5;27mbin[0m  LICENSE  Makefile  README.md  [38;5;27msrc[0m  [38;5;27mtests[0m
[m/home/csmajs/abarb014/cs100/rshell $ #   tee
hey
hey
mike
mike
and
and
taeyoung
taeyoung
^C
/home/csmajs/abarb014/cs100/rshell $ # Commands built by me in rshell
/home/csmajs/abarb014/cs100/rshell $ bin/ls
[38;5;27mbin/[0m         LICENSE[0m      Makefile[0m     README.md[0m    [38;5;27msrc/[0m         [38;5;27mtests/[0m       
/home/csmajs/abarb014/cs100/rshell $ bin/ls -l
total: 24
drwx------ 2 abarb014 csmajs 4096 Dec  4 10:16 [38;5;27mbin/[0m
-rw------- 1 abarb014 csmajs 94 Oct 16 10:05 LICENSE[0m
-rw------- 1 abarb014 csmajs 245 Nov 10 12:45 Makefile[0m
-rw------- 1 abarb014 csmajs 3557 Dec  1 09:36 README.md[0m
drwx------ 2 abarb014 csmajs 4096 Dec  4 10:07 [38;5;27msrc/[0m
drwx------ 2 abarb014 csmajs 4096 Dec  4 10:16 [38;5;27mtests/[0m
/home/csmajs/abarb014/cs100/rshell $ # Rshell n in Rshell (Rshell-ception)
/home/csmajs/abarb014/cs100/rshell $ bin/rshell
/home/csmajs/abarb014/cs100/rshell $ # commands in rshell in rhsell     shell
/home/csmajs/abarb014/cs100/rshell $ ls
bin  LICENSE  Makefile	README.md  src	tests
/home/csmajs/abarb014/cs100/rshell $ bin/ls -l
total: 24
drwx------ 2 abarb014 csmajs 4096 Dec  4 10:16 [38;5;27mbin/[0m
-rw------- 1 abarb014 csmajs 94 Oct 16 10:05 LICENSE[0m
-rw------- 1 abarb014 csmajs 245 Nov 10 12:45 Makefile[0m
-rw------- 1 abarb014 csmajs 3557 Dec  1 09:36 README.md[0m
drwx------ 2 abarb014 csmajs 4096 Dec  4 10:07 [38;5;27msrc/[0m
drwx------ 2 abarb014 csmajs 4096 Dec  4 10:16 [38;5;27mtests/[0m
/home/csmajs/abarb014/cs100/rshell $ pwd
/home/csmajs/abarb014/cs100/rshell
/home/csmajs/abarb014/cs100/rshell $ # exit back to main rshell and test make
/home/csmajs/abarb014/cs100/rshell $ exit
logout

[Process Completed]
/home/csmajs/abarb014/cs100/rshell $ make
mkdir -p bin
g++ -Wall -Werror -ansi -pedantic src/main.cpp -o bin/rshell
g++ -Wall -Werror -ansi -pedantic src/ls.cpp -o bin/ls
g++ -Wall -Werror -ansi -pedantic src/cp.cpp -o bin/cp
/home/csmajs/abarb014/cs100/rshell $ # Success
/home/csmajs/abarb014/cs100/rshell $ exit
logout

[Process Completed]
[s%%%%%%%%%%[u[0;32mabarb014[0;36m@[0;32mcs100[0;36m:[0;32m~/cs100/rshell[0;95m (signal) [0;36m$[0m clear
[H[2J[s%%%%%%%%%%[u[0;32mabarb014[0;36m@[0;32mcs100[0;36m:[0;32m~/cs100/rshell[0;95m (signal) [0;36m$[0m bin/sh[K[Krshell
/home/csmajs/abarb014/cs100/rshell $ # Testing the interrupt signl al ^C
/home/csmajs/abarb014/cs100/rshell $ # In rshell should do nothing
/home/csmajs/abarb014/cs100/rshell $ ^C
^C
^C
^C
^C
^C
^C
^C
ls
bin  LICENSE  Makefile	README.md  src	tests
/home/csmajs/abarb014/cs100/rshell $ # All good, now in a command like tee
/home/csmajs/abarb014/cs100/rshell $ tee
A Good
Good
^C
/home/csmajs/abarb014/cs100/rshell $ cat
better
better
^C
/home/csmajs/abarb014/cs100/rshell $ # in dual rshell
/home/csmajs/abarb014/cs100/rshell $ bin/rshell
/home/csmajs/abarb014/cs100/rshell $ #h  Here it prints an exr tra newlne  ine, b reported as a bug
/home/csmajs/abarb014/cs100/rshell $ ^C

^C

echo but it still works
but it still works
/home/csmajs/abarb014/cs100/rshell $ # Now in programs in dual rshell
/home/csmajs/abarb014/cs100/rshell $ tee
^C

/home/csmajs/abarb014/cs100/rshell $ echo just a new lin              works but prints an extra newline
works but prints an extra newline
/home/csmajs/abarb014/cs100/rshell $ exit
logout

[Process Completed]
/home/csmajs/abarb014/cs100/rshell $ # Back in main rshell, CD tests
/home/csmajs/abarb014/cs100/rshell $ # Basic CD usage
/home/csmajs/abarb014/cs100/rshell $ cd ..
/home/csmajs/abarb014/cs100 $ ls
lab  rshell  ucr-cs100
/home/csmajs/abarb014/cs100 $ cd rshell
/home/csmajs/abarb014/cs100/rshell $ ls
bin  LICENSE  Makefile	README.md  src	tests
/home/csmajs/abarb014/cs100/rshell $ # CD and do some cammands
/home/csmajs/abarb014/cs100/rshell $ cd src
/home/csmajs/abarb014/cs100/rshell/src $ ls
cp.cpp	ls.cpp	main.cpp  Timer.h
/home/csmajs/abarb014/cs100/rshell/src $ ls --color
cp.cpp  ls.cpp  main.cpp  Timer.h
/home/csmajs/abarb014/cs100/rshell/src $ pwd
/home/csmajs/abarb014/cs100/rshell/src
/home/csmajs/abarb014/cs100/rshell/src $ cat <   > file
heyo!
/home/csmajs/abarb014/cs100/rshell/src $ cat file
heyo!
/home/csmajs/abarb014/cs100/rshell/src $ cd ..
/home/csmajs/abarb014/cs100/rshell $ # # Change over several files
/home/csmajs/abarb014/cs100/rshell $ cd ..  /../
/home/csmajs/abarb014 $ ls
cs014  cs061  cs100  cs111  Desktop  Documents	Downloads  Music  Pictures  Public  Templates  Videos
/home/csmajs/abarb014 $ cd cs100/rshell/src
/home/csmajs/abarb014/cs100/rshell/src $ ls
cp.cpp	file  ls.cpp  main.cpp	Timer.h
/home/csmajs/abarb014/cs100/rshell/src $ rm file
/home/csmajs/abarb014/cs100/rshell/src $ ls
cp.cpp	ls.cpp	main.cpp  Timer.h
/home/csmajs/abarb014/cs100/rshell/src $ ../bin/ls
cp.cpp	ls.cpp	main.cpp  Timer.h
/home/csmajs/abarb014/cs100/rshell/src $ ps
  PID TTY          TIME CMD
39838 pts/19   00:00:00 bash
40018 pts/19   00:00:00 rshell
40273 pts/19   00:00:00 ps
/home/csmajs/abarb014/cs100/rshell/src $ # Thi   cd with no other argument
/home/csmajs/abarb014/cs100/rshell/src $ cd
chdir: Bad address
/home/csmajs/abarb014/cs100/rshell/src $ # directory stays the same
/home/csmajs/abarb014/cs100/rshell/src $ #cd     cd with too manu   y arguments
/home/csmajs/abarb014/cs100/rshell/src $ cd .. Hey Mike and Taet young
/home/csmajs/abarb014/cs100/rshell $ ls
bin  LICENSE  Makefile	README.md  src	tests
/home/csmajs/abarb014/cs100/rshell $ # oin  nlt th    y the d first argument is taken
/home/csmajs/abarb014/cs100/rshell $ # cd with invalid argument
/home/csmajs/abarb014/cs100/rshell $ cd make_believe_bro
chdir: No such file or directory
/home/csmajs/abarb014/cs100/rshell $ # fails as expected
/home/csmajs/abarb014/cs100/rshell $ ls
bin  LICENSE  Makefile	README.md  src	tests
/home/csmajs/abarb014/cs100/rshell $ # cd into a file
/home/csmajs/abarb014/cs100/rshell $ cd README.md
chdir: Not a directory
/home/csmajs/abarb014/cs100/rshell $ # fails as expected
/home/csmajs/abarb014/cs100/rshell $ # Some forge otten exec commands
/home/csmajs/abarb014/cs100/rshell $ # exec with an invalid proge ram
/home/csmajs/abarb014/cs100/rshell $ fire
my_exec: No such file or directory
/home/csmajs/abarb014/cs100/rshell $ # empty command
/home/csmajs/abarb014/cs100/rshell $ 
/home/csmajs/abarb014/cs100/rshell $ # cd to a far away directory
/home/csmajs/abarb014/cs100/rshell $ cd /
/ $ ls | tail -3
tmp
usr
var
/ $ # Had to do tail because theres so much in there!
/ $ #T  This concludes the testing
/ $ exit
logout

[Process Completed]
[s%%%%%%%%%%[u[0;32mabarb014[0;36m@[0;32mcs100[0;36m:[0;32m~/cs100/rshell[0;95m (signal) [0;36m$[0m clear[K[K[K[K[Kexit
exit
~
abarb014@hammer $ exit
exit

Script done on Thu 04 Dec 2014 10:30:41 AM PST
